### ISSUE TITLE
tests coverage reporting 

### ISSUE THREAD

**Issue by MaaniBeigy** [TezRomacH/python-package-template#368]
## 🚀 Feature Request
Tests coverage reporting.

## 🔈 Motivation

I found it in your [ToDos](https://github.com/TezRomacH/python-package-template#-todos). I implemented it for my own package [pycvcqv](https://github.com/MaaniBeigy/pycvcqv) using `pytest-cov`, [coverage-badge](https://github.com/dbrgn/coverage-badge), and, `pytest-html `.

## 🛰 Alternatives

To implement such a solution:

1. first, edit your `pyproject.toml`:

```toml
[tool.poetry.dev-dependencies]
coverage = "*"
coverage-badge = "*"
pytest-html = "*"
pytest-cov = "*"

[tool.coverage.run]
source = ['package_name', 'tests_folder']

[coverage.paths]

source = 'package_name'

[coverage.run]
branch = true

[coverage.report]
fail_under = 50
show_missing = true
```

2. next, `mkdir` assets/images/.
3. Then, add these lines to `Makefile`:

```Makefile
.PHONY: coverage
coverage:
	poetry run pytest --cov-report html --cov packagename tests/
	poetry run coverage-badge -o assets/images/coverage.svg -f
```

4. Then, run these lines:

```bash
make install
make test && make coverage && make check-codestyle && make mypy && make check-safety
```

5. Finally, add this to the `README.md`:

```markdown
[![coverage report](assets/images/coverage.svg)]
```

You, will have something like [![coverage report](https://raw.githubusercontent.com/MaaniBeigy/pycvcqv/main/assets/images/coverage.svg)](https://github.com/MaaniBeigy/pycvcqv).

## 📎 Additional context

More importantly, you can open `htmlcov/index.html` in your browser and observe the covered/uncovered codes. 

![image](https://user-images.githubusercontent.com/37554086/131194263-8eefad86-65f6-4419-a724-58c0e186492a.png)

![image](https://user-images.githubusercontent.com/37554086/131194499-c70580ff-5345-40f4-ace6-4348a1cc5355.png)
